-- MySQL Script generated by MySQL Workbench
-- Tue Dec  1 22:25:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

USE `amazon_go` ;

ALTER TABLE `amazon_go`.`cliente` ADD CONSTRAINT `PK_Cliente` PRIMARY KEY (`CPF`); 
ALTER TABLE `amazon_go`.`cesto_de_compras` ADD CONSTRAINT `PK_Cesto` PRIMARY KEY (`id_cesto`); 
ALTER TABLE `amazon_go`.`aplicativo` ADD CONSTRAINT `PK_aplicativo` PRIMARY KEY (`CPF_cliente`); 
ALTER TABLE `amazon_go`.`produto` ADD CONSTRAINT `PK_produto` PRIMARY KEY (`id_prod`); 
ALTER TABLE `amazon_go`.`franquia` ADD CONSTRAINT `PK_franquia` PRIMARY KEY (`id_franquia`); 
ALTER TABLE `amazon_go`.`funcionário` ADD CONSTRAINT `PK_funcionario` PRIMARY KEY (`id_funcionario`); 
ALTER TABLE `amazon_go`.`cesto_contem_produto` ADD CONSTRAINT `PK_cesto_contem_produto` PRIMARY KEY (`id_cesto_de_compras`, `id_do_produto`); 
ALTER TABLE `amazon_go`.`franquia possui produto` ADD CONSTRAINT `PK_franquia_possui_produto` PRIMARY KEY (`Produto_id_prod`, `Franquia_id_franquia`); 

ALTER TABLE `amazon_go`.`aplicativo` ADD CONSTRAINT `FK_CPF_Cliente` 
    FOREIGN KEY (`CPF_cliente`)
    REFERENCES `amazon_go`.`Cliente` (`CPF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE;
    
ALTER TABLE `amazon_go`.`aplicativo` ADD CONSTRAINT `FK_Cesto`  
    FOREIGN KEY (`Cesto de Compras`)
    REFERENCES `amazon_go`.`Cesto_de_Compras` (`id_cesto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

ALTER TABLE `amazon_go`.`funcionário` ADD CONSTRAINT `FK_funcionario`
    FOREIGN KEY (`Franquia`)
    REFERENCES `amazon_go`.`Franquia` (`id_franquia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

ALTER TABLE `amazon_go`.`cesto_contem_produto` ADD CONSTRAINT `FK_cesto_contem_produto_cesto`
    FOREIGN KEY (`id_cesto_de_compras`)
    REFERENCES `amazon_go`.`Cesto_de_Compras` (`id_cesto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE;
    
ALTER TABLE `amazon_go`.`cesto_contem_produto` ADD CONSTRAINT `FK_cesto_contem_produto_produto`
    FOREIGN KEY (`id_do_produto`)
    REFERENCES `amazon_go`.`Produto` (`id_prod`)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

ALTER TABLE `amazon_go`.`franquia possui produto` ADD CONSTRAINT `FK_franquia_possui_produto_produto` 
    FOREIGN KEY (`Produto_id_prod`)
    REFERENCES `amazon_go`.`Produto` (`id_prod`)
    ON DELETE CASCADE
    ON UPDATE CASCADE;
    
ALTER TABLE `amazon_go`.`franquia possui produto` ADD CONSTRAINT `FK_franquia_possui_produto_franquia` 
    FOREIGN KEY (`Franquia_id_franquia`)
    REFERENCES `amazon_go`.`Franquia` (`id_franquia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
