-- MySQL Script generated by MySQL Workbench
-- Tue Dec  1 22:13:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

USE `amazon_go` ;

CREATE UNIQUE INDEX `CPF_UNIQUE` ON `amazon_go`.`Cliente` (`CPF` ASC) VISIBLE;
CREATE INDEX `Cartão de Crédito` ON `amazon_go`.`Cliente` (`Cartões de Crédito` ASC) VISIBLE;

CREATE INDEX `Cesto de Compras_UNIQUE` ON `amazon_go`.`Aplicativo` (`Cesto de Compras` ASC) INVISIBLE;

CREATE INDEX `localização` ON `amazon_go`.`Produto` (`Setor` ASC, `Prateleira` ASC) INVISIBLE;
CREATE INDEX `validade` ON `amazon_go`.`Produto` (`Data de Validade` ASC) INVISIBLE;
CREATE INDEX `lote` ON `amazon_go`.`Produto` (`Lote` ASC) VISIBLE;
CREATE INDEX `preço` ON `amazon_go`.`Produto` (`Preço` ASC) VISIBLE;

CREATE UNIQUE INDEX `CNPJ_UNIQUE` ON `amazon_go`.`Franquia` (`CNPJ` ASC) VISIBLE;
CREATE UNIQUE INDEX `Endereço_UNIQUE` ON `amazon_go`.`Franquia` (`Endereço` ASC) VISIBLE;

CREATE UNIQUE INDEX `CPF_UNIQUE` ON `amazon_go`.`Funcionário` (`CPF` ASC) VISIBLE;
CREATE INDEX `FK_franquia_idx` ON `amazon_go`.`Funcionário` (`Franquia` ASC) VISIBLE;

CREATE INDEX `fk_Cesto de Compras_has_Produto_Produto1_idx` ON `amazon_go`.`Cesto_contem_Produto` (`id_do_produto` ASC) VISIBLE;
CREATE INDEX `fk_Cesto de Compras_has_Produto_Cesto de Compras1_idx` ON `amazon_go`.`Cesto_contem_Produto` (`id_cesto_de_compras` ASC) VISIBLE;

CREATE INDEX `fk_Produto_has_Franquia_Franquia1_idx` ON `amazon_go`.`Franquia possui Produto` (`Franquia_id_franquia` ASC) VISIBLE;
CREATE INDEX `fk_Produto_has_Franquia_Produto1_idx` ON `amazon_go`.`Franquia possui Produto` (`Produto_id_prod` ASC) VISIBLE;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
