-- MySQL Script generated by MySQL Workbench
-- Tue Dec 1 21:05:53 2020
-- Model: New Model Version: 2.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,'
'NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
DROP SCHEMA IF EXISTS `amazon_go`;
CREATE SCHEMA IF NOT EXISTS `amazon_go` DEFAULT CHARACTER SET utf8 ;
USE `amazon_go` ;
DROP TABLE IF EXISTS `amazon_go`.`Aplicativo` ;
DROP TABLE IF EXISTS `amazon_go`.`Cesto_de_Compras` ;
DROP TABLE IF EXISTS `amazon_go`.`Cliente` ;
DROP TABLE IF EXISTS `amazon_go`.`Franquia` ;
DROP TABLE IF EXISTS `amazon_go`.`Funcionário` ;
DROP TABLE IF EXISTS `amazon_go`.`Produto` ;
DROP TABLE IF EXISTS `amazon_go`.`Cesto_contem_Produto` ;
DROP TABLE IF EXISTS `amazon_go`.`Franquia possui Produto` ;
CREATE TABLE IF NOT EXISTS `amazon_go`.`Cliente` (
`CPF` INT NOT NULL,
`Nome` VARCHAR(45) NOT NULL,
`Endereço` VARCHAR(45) NOT NULL,
`E-mail` VARCHAR(45) NOT NULL,
`Cartões de Crédito` VARCHAR(45) NOT NULL,
`Data de Nascimento` DATE NOT NULL)
ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS `amazon_go`.`Cesto_de_Compras` (
`id_cesto` INT NOT NULL,
`valor_total` FLOAT ZEROFILL UNSIGNED NULL)
ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS `amazon_go`.`Aplicativo` (
`CPF_cliente` INT NOT NULL,
`Cesto de Compras` INT NULL,
`Histórico` VARCHAR(45) NULL)
ENGINE= InnoDB;
CREATE TABLE IF NOT EXISTS `amazon_go`.`Franquia` (
`id_franquia` INT NOT NULL,
`CNPJ` VARCHAR(45) NOT NULL,
`Endereço` VARCHAR(45) NOT NULL)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `amazon_go`.`Funcionário` (
`id_funcionario` INT NOT NULL,
`Cargo` VARCHAR(45) NOT NULL,
`Nome` VARCHAR(45) NOT NULL,
`CPF` INT UNSIGNED NOT NULL,
`Franquia` INT NOT NULL)
ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS `amazon_go`.`Produto` (
`id_prod` INT NOT NULL,
`Setor` VARCHAR(45) NOT NULL,
`prateleira` VARCHAR(45) NOT NULL,
`Nome` VARCHAR(45) NOT NULL,
`Marca` VARCHAR(45) NOT NULL,
`Data de Validade` DATE NOT NULL,
`Lote` VARCHAR(45) NOT NULL,
`Preço` FLOAT ZEROFILL UNSIGNED NOT NULL)
ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS `amazon_go`.`Cesto_contem_Produto` (
`id_cesto_de_compras` INT NOT NULL,
`id_do_produto` INT NOT NULL)
ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS `amazon_go`.`Franquia possui Produto` (
`Produto_id_prod` INT NOT NULL,
`Franquia_id_franquia` INT NOT NULL)
ENGINE = InnoDB;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
